export const ConvertsMonth = {
  Jan: "01",
  Feb: "02",
  Mar: "03",
  Apr: "04",
  May: "05",
  Jun: "06",
  Jul: "07",
  Aug: "08",
  Sep: "09",
  Oct: "10",
  Nov: "11",
  Dec: "12",
};
export const CAN_NAM = [
  "Canh",
  "Tân",
  "Nhâm",
  "Quý",
  "Giáp",
  "Ất",
  "Bính",
  "Đinh",
  "Mậu",
  "Kỷ",
];
export const CHI_NAM = [
  "Thân",
  "Dậu",
  "Tuất",
  "Hợi",
  "Tý",
  "Sửu",
  "Dần",
  "Mão",
  "Thìn",
  "Tỵ",
  "Ngọ",
  "Mùi",
];
export const CHI_NAM_SORTED = [
  "Tý",
  "Sửu",
  "Dần",
  "Mão", //
  "Thìn",
  "Tỵ",
  "Ngọ",
  "Mùi",
  "Thân",
  "Dậu", //
  "Tuất",
  "Hợi",
];
export const TRUC_XUNG_HAI = {
  Tý: ["Ngọ", "Mùi", "Tý"],
  Sửu: ["Mùi", "Ngọ", "Sửu"],
  Dần: ["Thân", "Tỵ", "Dần"],
  Mão: ["Dậu", "Thìn", "Mão"],
  Thìn: ["Tuất", "Mão", "Thìn"],
  Tỵ: ["Hợi", "Dần", "Tỵ"],
  Ngọ: ["Tý", "Sửu", "Ngọ"],
  Mùi: ["Sửu", "Tý", "Mùi"],
  Thân: ["Dần", "Hợi", "Thân"],
  Dậu: ["Mão", "Tuất", "Dậu"],
  Tuất: ["Thìn", "Dậu", "Tuất"],
  Hợi: ["Tỵ", "Thân", "Hợi"],
};
export const DIA_CHI_HINH = {
  Tý: ["Mão"],
  Sửu: ["Mùi", "Tuất"],
  Dần: ["Thân", "Tỵ"],
  Mão: ["Tý"],
  Thìn: [],
  Tỵ: ["Dần", "Thân"],
  Ngọ: [],
  Mùi: ["Sửu", "Tuất"],
  Thân: ["Dần", "Tỵ"],
  Dậu: [],
  Tuất: ["Sửu", "Mùi"],
  Hợi: [],
};
export const GIO_THO_TU = {
  Tý: "Sửu",
  Sửu: "Ngọ",
  Dần: "Ngọ",

  Mão: "Mão",

  Thìn: "Tỵ",
  Tỵ: "Tỵ",
  Ngọ: "Tỵ",
  Mùi: "Mùi",
  Thân: "Mùi",
  Dậu: "Ngọ",
  Tuất: "Ngọ",
  Hợi: "Ngọ",
};
export const GIO_SAT_CHU = [
  "Dần",
  "Tỵ",
  "Thân",
  "Thìn",
  "Dậu",
  "Mão",
  "Dần",
  "Tỵ",
  "Thân",
  "Thìn",
  "Dậu",
  "Mão",
];

export const NGU_HANH_TUONG_SINH = {
  Kim: ["Thuỷ", "Kim", "Thổ"],
  Mộc: ["Thuỷ", "Mộc", "Hoả"],
  Thổ: ["Hoả", "Thổ", "Kim"],
  Thuỷ: ["Kim", "Thuỷ", "Mộc"],
  Hoả: ["Mộc", "Hoả", "Thổ"],
  "": [""],
};
export const NGU_HANH_TUONG_KHAC = {
  Kim: ["Mộc", "Hoả"],
  Mộc: ["Thổ", "Kim"],
  Thổ: ["Thuỷ", "Mộc"],
  Thuỷ: ["Hoả", "Thổ"],
  Hoả: ["Kim", "Thuỷ"],
  "": [""],
};
export const NGU_HANH_TUONG_KHAC_KHAU_QUYET = {
  Kim: "Mộc",
  Mộc: "Thổ",
  Thổ: "Thuỷ",
  Thuỷ: "Hoả",
  Hoả: "Kim",
  "": "",
};
export const NGU_HANH = {
  "": "",
  Tý: "Thuỷ",
  Sửu: "Thổ",
  Dần: "Mộc",
  Mão: "Mộc",
  Thìn: "Thổ",
  Tỵ: "Hoả",
  Ngọ: "Hoả",
  Mùi: "Thổ",
  Thân: "Kim",
  Dậu: "Kim",
  Tuất: "Thổ",
  Mậu: "Thổ",
  Kỷ: "Thổ",
  Hợi: "Thuỷ",

  Giáp: "Mộc",
  Ất: "Mộc",
  Bính: "Hoả",
  Đinh: "Hoả",
  Canh: "Kim",
  Tân: "Kim",
  Nhâm: "Thuỷ",
  Quý: "Thuỷ",

  Cấn: "Thổ",
  Tốn: "Mộc",
  Khôn: "Thổ",
  Càn: "Kim",
};
export const TAM_HOP = {
  Tý: ["Thân", "Thìn"],
  Sửu: ["Tỵ", "Dậu"],
  Dần: ["Ngọ", "Tuất"],
  Mão: ["Hợi", "Mùi"],

  Thìn: ["Thân", "Tý"],
  Tỵ: ["Sửu", "Dậu"],
  Ngọ: ["Dần", "Tuất"],
  Mùi: ["Hợi", "Mão"],

  Thân: ["Tý", "Thìn"],
  Dậu: ["Tỵ", "Sửu"],
  Tuất: ["Ngọ", "Dần"],
  Hợi: ["Mão", "Mùi"],
};
export const NHI_HOP = {
  Tý: ["Sửu"],
  Sửu: ["Tý"],
  Dần: ["Hợi"],
  Mão: ["Tuất"],

  Thìn: ["Dậu"],
  Tỵ: ["Thân"],
  Ngọ: ["Mùi"],
  Mùi: ["Ngọ"],

  Thân: ["Tỵ"],
  Dậu: ["Dậu"],
  Tuất: ["Tuất"],
  Hợi: ["Dần"],
};
export const TAM_TAI = {
  Tý: ["Mão", "Dần", "Thìn"],
  Thân: ["Mão", "Dần", "Thìn"],
  Thìn: ["Mão", "Dần", "Thìn"],

  Dần: ["Thân", "Dậu", "Tuất"],
  Ngọ: ["Thân", "Dậu", "Tuất"],
  Tuất: ["Thân", "Dậu", "Tuất"],

  Hợi: ["Tỵ", "Ngọ", "Mùi"],
  Mão: ["Tỵ", "Ngọ", "Mùi"],
  Mùi: ["Tỵ", "Ngọ", "Mùi"],

  Tỵ: ["Tý", "Sửu", "Hợi"],
  Dậu: ["Tý", "Sửu", "Hợi"],
  Sửu: ["Tý", "Sửu", "Hợi"],
};
export const COMBINE_THIEN_CAN = [
  ["Giáp", "Kỷ", "Thổ"],
  ["Ất", "Canh", "Kim"],
  ["Bính", "Tân", "Thuỷ"],
  ["Đinh", "Nhâm", "Mộc"],
  ["Mậu", "Quý", "Hoả"],
];
export const THIEN_TAI_DIA_HOA = {
  Tý: [1, 5, 9],
  Ngọ: [3, 7, 11],
  Mão: [2, 6, 10],
  Dậu: [4, 8, 12],
};
export const DAI_BAI = {
  Giáp: { 3: "Mậu Tuất", 7: "Quý Hợi", 10: "Bính Thân", 11: "Đinh Hợi" },
  Kỷ: { 3: "Mậu Tuất", 7: "Quý Hợi", 10: "Bính Thân", 11: "Đinh Hợi" },

  Ất: { 4: "Nhâm Thân", 9: "Ất Tỵ" },
  Canh: { 4: "Nhâm Thân", 9: "Ất Tỵ" },

  Bính: { 3: "Tân Tỵ", 9: "Canh Thìn" },
  Tân: { 3: "Tân Tỵ", 9: "Canh Thìn" },

  Mậu: { 6: "Kỷ Sửu" },
  Quý: { 6: "Kỷ Sửu" },
};
export const DUONG_CONG = [
  [13],
  [11],
  [9],
  [7],
  [5],
  [3],
  [8, 29],
  [27],
  [25],
  [23],
  [21],
  [19],
];
export const HOANG_OC = [
  "Nhất Cát",
  "Nhị Nghi",
  "Tam Địa sát",
  "Tứ Tấn tài",
  "Ngũ Thọ tử",
  "Lục Hoang ốc",
];
export const HOANG_VU_TU_QUY = {
  Xuân: "Thân",
  Hạ: "Dần",
  Thu: "Thìn",
  Đông: "Tỵ",
};
export const KHONG_PHONG = {
  Xuân: ["Thìn", "Tỵ", "Tý"],
  Hạ: ["Tuất", "Hợi", "Mùi"],
  Thu: ["Mão", "Dần", "Ngọ"],
  Đông: ["Thân", "Dậu", "Sửu"],
};
export const THO_TU = [
  "Tuất",
  "Thìn",
  "Hợi",
  "Tỵ",
  "Tý",
  "Ngọ",
  "Sửu",
  "Mùi",
  "Dần",
  "Thân",
  "Mão",
  "Dậu",
];
export const SAT_CHU_AM = [
  "Tỵ",
  "Tý",
  "Mùi",
  "Mão",
  "Thân",
  "Tuất",
  "Hợi",
  "Sửu",
  "Ngọ",
  "Dậu",
  "Dần",
  "Thìn",
];
export const SAT_CHU_DUONG = [
  "Tý",
  "Sửu",
  "Sửu",
  "Tuất",
  "Thìn",
  "Thìn",
  "Sửu",
  "Thìn",
  "Sửu",
  "Thìn",
  "Mùi",
  "Thìn",
];
export const VANG_VONG = [
  "Dần",
  "Tỵ",
  "Thân",
  "Hợi",
  "Mão",
  "Ngọ",
  "Dậu",
  "Tý",
  "Thìn",
  "Mùi",
  "Tuất",
  "Sửu",
];
export const NGUYET_PHA = [
  "Thân",
  "Dậu",
  "Tuất",
  "Hợi",
  "Tý",
  "Sửu",
  "Dần",
  "Mão",
  "Thìn",
  "Tỵ",
  "Ngọ",
  "Mùi",
];
export const TAM_NUONG = [3, 7, 13, 18, 22, 27];
export const NGUYET_KY = [5, 14, 23];
export const CAN_CHI_THANG = [
  // 'Canh', Ất
  [
    "Mậu Dần",
    "Kỷ Mão",
    "Canh Thìn",
    "Tân Tỵ",
    "Nhâm Ngọ",
    "Quý Mùi",
    "Giáp Thân",
    "Ất Dậu",
    "Bính Tuất",
    "Đinh Hợi",
    "Mậu Tý",
    "Kỷ Sửu",
  ],
  //   'Tân', Bính
  [
    "Canh Dần",
    "Tân Mão",
    "Nhâm Thìn",
    "Quý Tỵ",
    "Giáp Ngọ",
    "Ất Mùi",
    "Bính Thân",
    "Đinh Dậu",
    "Mậu Tuất",
    "Kỷ Hợi",
    "Canh Tý",
    "Tân Sửu",
  ],

  //    'Nhâm', Đinh
  [
    "Nhâm Dần",
    "Quý Mão",
    "Giáp Thìn",
    "Ất Tỵ",
    "Bính Ngọ",
    "Đinh Mùi",
    "Mậu Thân",
    "Kỷ Dậu",
    "Canh Tuất",
    "Tân Hợi",
    "Nhâm Tý",
    "Quý Sửu",
  ],

  // 'Quý', Mậu
  [
    "Giáp Dần",
    "Ất Mão",
    "Bính Thìn",
    "Đinh Tỵ",
    "Mậu Ngọ",
    "Kỷ Mùi",
    "Canh Thân",
    "Tân Dậu",
    "Nhâm Tuất",
    "Quý Hợi",
    "Giáp Tý",
    "Ất Sửu",
  ],
  //Giáp,Kỷ
  [
    "Bính Dần",
    "Đinh Mão",
    "Mậu Thìn",
    "Kỷ Tỵ",
    "Canh Ngọ",
    "Tân Mùi",
    "Nhâm Thân",
    "Quý Dậu",
    "Giáp Tuất",
    "Ất Hợi",
    "Bính Tý",
    "Đinh Sửu",
  ],
];
export const CAN_NGAY = [
  "Giáp",
  "Ất",
  "Bính",
  "Đinh",
  "Mậu",
  "Kỷ",
  "Canh",
  "Tân",
  "Nhâm",
  "Quý",
];
export const CHI_NGAY = [
  "Tý",
  "Sửu",
  "Dần",
  "Mão",
  "Thìn",
  "Tỵ",
  "Ngọ",
  "Mùi",
  "Thân",
  "Dậu",
  "Tuất",
  "Hợi",
];
export const GIO_DIA_CHI = [
  "23-1",
  "1-3",
  "3-5",
  "5-7",
  "7-9",
  "9-11",
  "11-13",
  "13-15",
  "15-17",
  "17-19",
  "19-21",
  "21-23",
];
export const CHI_HOANG_DAO = {
  Tý: ["Tý", "Sửu", "Mão", "Ngọ", "Thân", "Dậu"],
  Sửu: ["Dần", "Mão", "Tỵ", "Thân", "Tuất", "Hợi"],
  Dần: ["Tý", "Sửu", "Thìn", "Tỵ", "Mùi", "Tuất"],
  Mão: ["Tý", "Dần", "Mão", "Ngọ", "Mùi", "Dậu"],
  Thìn: ["Dần", "Thìn", "Tỵ", "Thân", "Dậu", "Hợi"],
  Tỵ: ["Sửu", "Thìn", "Tỵ", "Thân", "Dậu", "Hợi"],
  Ngọ: ["Tý", "Sửu", "Mão", "Ngọ", "Thân", "Dậu"],
  Mùi: ["Dần", "Mão", "Tỵ", "Thân", "Tuất", "Hợi"],
  Thân: ["Tý", "Sửu", "Thìn", "Tỵ", "Mùi", "Tuất"],
  Dậu: ["Tý", "Dần", "Mão", "Ngọ", "Mùi", "Dậu"],
  Tuất: ["Dần", "Thìn", "Tỵ", "Thân", "Dậu", "Hợi"],
  Hợi: ["Sửu", "Thìn", "Tỵ", "Thân", "Dậu", "Hợi"],
};
export const GIO_HOANG_DAO = {
  Thân: "Tý (23-1), Sửu (1-3), Thìn (7-9), Tỵ (9-11), Mùi (13-15), Tuất (19-21)",
  Dậu: "Tý (23-1), Dần (3-5), Mão (5-7), Ngọ (11-13), Mùi (13-15), Dậu (17-19)",
  Tuất: "Dần (3-5), Thìn (7-9), Tỵ (9-11), Thân (15-17), Dậu (17-19), Hợi (21-23)",
  Hợi: "Sửu (1-3), Thìn (7-9), Ngọ (11-13), Mùi (13-15), Tuất (19-21), Hợi (21-23)",
  Tý: "Tý (23-1), Sửu (1-3), Mão (5-7), Ngọ (11-13), Thân (15-17), Dậu (17-19)",
  Sửu: "Dần (3-5), Mão (5-7), Tỵ (9-11), Thân (15-17), Tuất (19-21), Hợi (21-23)",
  Dần: " Tý (23-1), Sửu (1-3), Thìn (7-9), Tỵ (9-11), Mùi (13-15), Tuất (19-21)",
  Mão: "Tý (23-1), Dần (3-5), Mão (5-7), Ngọ (11-13), Mùi (13-15), Dậu (17-19)",
  Thìn: "Dần (3-5), Thìn (7-9), Tỵ (9-11), Thân (15-17), Dậu (17-19), Hợi (21-23)",
  Tỵ: "Sửu (1-3), Thìn (7-9), Ngọ (11-13), Mùi (13-15), Tuất (19-21), Hợi (21-23)",
  Ngọ: "Tý (23-1), Sửu (1-3), Mão (5-7), Ngọ (11-13), Thân (15-17), Dậu (17-19)",
  Mùi: "Dần (3-5), Mão (5-7), Tỵ (9-11), Thân (15-17), Tuất (19-21), Hợi (21-23)",
};
export const NGAYHOANGDAO_NGAYHACDAO = [
  // mod 6  = 0
  {
    hoangDao: ["Mão", "Tuất", "Tỵ", "Hợi", "Dần", "Thân"],
    hacDao: ["Thìn", "Sửu", "Mùi", "Dậu", "Tý", "Ngọ"],
  },
  // mod 6  = 1
  {
    hoangDao: ["Tý", "Sửu", "Tỵ", "Mùi", "Thìn", "Tuất"],
    hacDao: ["Ngọ", "Mão", "Hợi", "Dậu", "Dần", "Thân"],
  },
  // mod 6  = 2
  {
    hoangDao: ["Dần", "Mão", "Dậu", "Mùi", "Ngọ", "Tý"],
    hacDao: ["Thân", "Tỵ", "Hợi", "Sửu", "Thìn", "Tuất"],
  },
  // mod 6  = 3
  {
    hoangDao: ["Thìn", "Dậu", "Tỵ", "Hợi", "Thân", "Dần"],
    hacDao: ["Tuất", "Mùi", "Mão", "Sửu", "Ngọ", "Tý"],
  },
  // mod 6  = 4
  {
    hoangDao: ["Ngọ", "Sửu", "Thìn", "Mùi", "Tuất", "Hợi"],
    hacDao: ["Thân", "Tý", "Mão", "Tỵ", "Dậu", "Dần"],
  },
  // mod 6  = 5
  {
    hoangDao: ["Mão", "Sửu", "Thân", "Dậu", "Tý", "Ngọ"],
    hacDao: ["Dần", "Mùi", "Hợi", "Tỵ", "Tuất", "Dậu"],
  },
];
export const CAN = [
  "Giáp",
  "Ất",
  "Bính",
  "Đinh",
  "Mậu",
  "Kỷ",
  "Canh",
  "Tân",
  "Nhâm",
  "Quý",
];
export const CHI = [
  "Tý",
  "Sửu",
  "Dần",
  "Mão",
  "Thìn",
  "Tỵ",
  "Ngọ",
  "Mùi",
  "Thân",
  "Dậu",
  "Tuất",
  "Hợi",
];
export const CHI_GIO_TANG_SU = [
  "Tý",
  "Sửu",
  "Mão",
  "Thìn",
  "Ngọ",
  "Mùi",
  "Dậu",
  "Tuất",
];
export const TUAN = [
  "Chủ Nhật",
  "Thứ Hai",
  "Thứ Ba",
  "Thứ Tư",
  "Thứ Năm",
  "Thứ Sáu",
  "Thứ Bảy",
];

export const C_H = [
  0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
  0, 0,
];
export const THANG_AM_VN = [
  "Một",
  "Hai",
  "Ba",
  "Bốn",
  "Năm",
  "Sáu",
  "Bảy",
  "Tám",
  "Chín",
  "Mười",
  "Mười một",
  "Mười hai",
];
export const TIETKHI = [
  "Xuân phân", //0:
  "Thanh minh", //15:
  "Cốc vũ", //30:
  "Lập hạ", //45:
  "Tiểu mãn", //60:
  "Mang chủng", //75:
  "Hạ chí", //90:
  "Tiểu thử", //105:
  "Đại thử", //120:
  "Lập thu", //135:
  "Xử thử", //150:
  "Bạch lộ", //165:
  "Thu phân", //180:
  "Hàn lộ", //195:
  "Sương giáng", //210:
  "Lập đông", //225:
  "Tiểu tuyết", //240:
  "Đại tuyết", //255:
  "Đông chí", //270:
  "Tiểu hàn", //285:
  "Đại hàn", //300:
  "Lập xuân", //315:
  "Vũ thủy", //330:
  "Kinh trập", //345:
];
export const ObjectTruc = {
  Kiến: {
    CanLam: {
      "trong-cay": "Trồng cây",
      "khai-truong": "Khai trương",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhap-kho": "Ngày nhập kho",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",
    },
    KhongLam: {
      "dong-tho": "Động thổ",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "dao-gieng": "Đào giếng",
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "ha-tieu": "Hạ tiểu",
    },
  },
  Trừ: {
    CanLam: {
      "boc-bat-huong": "Bốc bát hương",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",
    },
    KhongLam: {
      "khai-truong": "Khai trương",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
    },
  },
  Mãn: {
    CanLam: {
      "sua-chua": "Sửa chữa",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",
    },
    KhongLam: {
      "ngay-nham-chuc": "Ngày nhậm chức",
      "kien-tung": "Kiện tụng",
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "ha-tieu": "Hạ tiểu",
    },
  },
  Bình: {
    CanLam: {
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nhap-kho": "Ngày nhập kho",
      "ngay-xuat-hang": "Ngày xuất hàng",
    },
    KhongLam: {},
  },
  Định: {
    CanLam: {
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nhap-kho": "Ngày nhập kho",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
    },
    KhongLam: {
      "kien-tung": "Kiện tụng",
    },
  },
  Chấp: {
    CanLam: {
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
    },
    KhongLam: {
      "kien-tung": "Kiện tụng",
      "khai-truong": "Khai trương",
      "xuat-hanh": "Xuất hành",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
    },
  },
  Phá: {
    CanLam: {
      "pha-do": "Phá dỡ",
      "chuyen-nha": "Chuyển nhà",
      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",
    },
    KhongLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "ban-nha": "Bán nhà",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Ngày lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
      "ta-dat": "Tạ mộ",
    },
  },
  Nguy: {
    CanLam: {
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",
    },
    KhongLam: {
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "trong-cay": "Trồng cây",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },
  Thành: {
    CanLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đập",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "xuat-hanh": "Xuất hành",

      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",

      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",
      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu iêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {
      "kien-tung": "Kiện tụng",
    },
  },
  Thu: {
    CanLam: {
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
    },
    KhongLam: {
      "ha-huyet": "Hạ huyệt",
      "ta-mo": "Tạ mộ",
    },
  },
  Khai: {
    CanLam: {
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "trong-cay": "Trồng cây",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",

      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",

      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",

      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",
      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu iêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",

      "ta-mo": "Tạ mộ",
    },
    KhongLam: {
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
    },
  },
  Bế: {
    CanLam: {
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "lap-gieng": "Lắp giếng",
    },
    KhongLam: {
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "trong-cay": "Trồng cây",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dao-gieng": "Đào giếng",

      "kien-tung": "Kiện tụng",

      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",

      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",

      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",
      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu iêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },
};

export const ObjectTu = {
  Giác: {
    CanLam: {
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
    },
    KhongLam: {
      "ha-huyet": "Hạ huyệt",
      "ha-tieu": "Hạ tiểu",
    },
  },
  Cang: {
    CanLam: {},
    KhongLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },
  Đê: {
    CanLam: {
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
    },
    KhongLam: {
      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },
  Phòng: {
    CanLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {},
  },
  Tâm: {
    CanLam: {},
    KhongLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },
  Vĩ: {
    CanLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {},
  },
  Cơ: {
    CanLam: {
      "khai-truong": "Khai trương",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",

      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",
    },
    KhongLam: {},
  },
  Đẩu: {
    CanLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "nhap-trach": "Nhập trạch",
      "khai-truong": "Khai trương",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "ha-tieu": "Hạ tiểu",
    },
    KhongLam: {},
  },
  Ngưu: {
    CanLam: {},
    KhongLam: {
      "dong-tho": "Động thổ",
      "nhap-trach": "Nhập trạch",
      "khai-truong": "Khai trương",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",
    },
  },
  Nữ: {
    CanLam: {},
    KhongLam: {
      "ngay-nham-chuc": "Ngày nhậm chức",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",
    },
  },
  Hư: {
    CanLam: {},
    KhongLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },

  Nguy: {
    CanLam: {},
    KhongLam: {
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "dung-bia": "Dựng bia",
      "ha-huyet": "Hạ huyệt",
    },
  },
  Thất: {
    CanLam: {
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "khai-truong": "Khai trương",
      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {},
  },
  Bích: {
    CanLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {},
  },
  Khuê: {
    CanLam: {
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
    },
    KhongLam: {
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "dong-tho": "Động thổ",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "dao-gieng": "Đào giếng",
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "ha-tieu": "Hạ tiểu",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "dung-bia": "Dựng bia",
      "ha-huyet": "Hạ huyệt",
    },
  },
  Lâu: {
    CanLam: {
      "sua-chua": "Sửa chữa",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "trong-cay": "Trồng cây",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "lap-gieng": "Lắp giếng",
      "dao-gieng": "Đào giếng",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",

      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",

      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",

      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",
      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu iêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {
      "ngay-nham-chuc": "Ngày nhậm chức",
      "kien-tung": "Kiện tụng",
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "ha-tieu": "Hạ tiểu",
    },
  },
  Vị: {
    CanLam: {
      "boc-bat-huong": "Bốc bát hương",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",
      "sua-chua": "Sửa chữa",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "trong-cay": "Trồng cây",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "lap-gieng": "Lắp giếng",
      "dao-gieng": "Đào giếng",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",

      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",

      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",

      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",
      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu iêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {},
  },
  Mão: {
    CanLam: {},
    KhongLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },
  Tất: {
    CanLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {},
  },
  Chủy: {
    CanLam: {},
    KhongLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },

  Sâm: {
    CanLam: {
      "sua-chua": "Sửa chữa",
      "khai-truong": "Khai trương",
      "nhap-hoc": "Nhập học",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
    },
    KhongLam: {
      "ha-huyet": "Hạ huyệt",
      "ha-tieu": "Hạ tiểu",
    },
  },
  Tỉnh: {
    CanLam: {
      "sua-chua": "Sửa chữa",
      "khai-truong": "Khai trương",
      "nhap-hoc": "Nhập học",
    },
    KhongLam: {
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
    },
  },
  Quỷ: {
    CanLam: {
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",
      "ha-tieu": "Hạ tiểu",
    },
    KhongLam: {
      "dong-tho": "Động thổ",
      "khai-truong": "Khai trương",
      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",
    },
  },
  Liễu: {
    CanLam: {},
    KhongLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },
  Tinh: {
    CanLam: {
      "khoi-cong": "Khởi công",
    },
    KhongLam: {
      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",
    },
  },
  Trương: {
    CanLam: {},
    KhongLam: {
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "dong-tho": "Động thổ",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
    },
  },
  Dực: {
    CanLam: {
      "dong-tho": "Động thổ",
      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",
    },
    KhongLam: {
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
    },
  },

  Chẩn: {
    CanLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {},
  },
};
export const COLOR_TEXT_NGU_HANH = {
  Hoả: "red",
  Mộc: "green",
  Kim: "#f2ca02",
  Thuỷ: "blue",
  Thổ: "brown",
};
export const SERVICE_XAYDUNG = {
  "trong-cay": "Trồng cây",
  "khoi-cong": "Khởi công",
  "sua-chua": "Sửa chữa",
  "pha-do": "Phá dỡ",
  "dong-tho": "Động thổ",
  "do-mong": "Đổ móng",
  "do-mai": "Đổ mái",
  "cat-noc": "Cất nóc",
  "mo-cong": "Mở cổng",
  "boi-hoan-long-mach": "Bồi hoàn long mạch",
  "nhap-trach": "Nhập trạch",
  "ta-dat": "Tạ đất",
  "khanh-thanh": "Khánh thành",
  "khai-truong": "Khai trương",
  "mo-cua-hang": "Mở cửa hàng",
  "chuyen-nha": "Chuyển nhà",
  "ban-nha": "Bán nhà",
  "dap-dap": "Đắp đập",
  "ngan-de": "Ngăn đê",
  "dao-gieng": "Đào giếng",
  "lap-gieng": "Lắp giếng",
};
export const SERVICE_THOCUNG = {
  "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
  "boc-bat-huong": "Bốc bát hương",
  "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
  "dang-them-vat-pham": "Dâng thêm vât phẩm",
  "them-bat-huong": "Thêm bát hương cho bàn thờ",
  "thay-ban-tho": "Thay bàn thờ mới",
  "giai-xa-ban-tho": "Giải xá bàn thờ",
  "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
  "le-cau":
    "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",
};
export const SERVICE_SUCKHOE = {
  "ngay-kham-benh": "Ngày khám bệnh",
  "ngay-phau-thuat": "Ngày phẫu thuật",
};
export const SERVICE_CONGVIECDAISU = {
  "xuat-hanh": "Xuất hành",
  "mua-ban-lon":
    "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
  "ngay-nham-chuc": "Ngày nhậm chức",
  "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
  "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
  "ngay-xuat-hang": "Ngày xuất hàng",
  "ngay-xuat-hang": "Ngày xuất hàng",
  "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
  "ngay-thuc-hien-du-an":
    "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
  "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
  "cung-xe-moi": "Cúng xe mới",
  "to-chuc-cac-su-kien": "Tổ chức các sự kiện",
};
export const SERVICE_CUOIHOI = {
  "ngay-mai-moi": "Ngày mai mối",
  "ngay-dam-ngo": "Ngày dạm ngõ",
  "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
  "ngay-lai-mat": "Ngày lại mặt",
  "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
  "ngay-cuoi": "Ngày cưới (xin dâu, đón dâu)",
};
export const SERVICE_TANGSU = {
  "tinh-trung-tang": "Tính trùng tang",
  "kham-niem": "Khâm niệm",
  "nhap-quan": "Nhập quan",
  "di-quan": "Di quan",
  "ha-huyet": "Hạ huyệt",
};
export const SERVICE_SANGCAT = {
  "dong-tho-xay-ho": "Động thổ xây hố",
  "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
  "kham-liem": "Khâm liệm",
  "ha-tieu": "Hạ tiểu",
  "dung-bia": "Dựng bia",
  "ta-mo": "Tạ mộ",
  "ta-dat": "Tạ mộ",
};

export const MONTHS = [
  "Tháng 1",
  "Tháng 2",
  "Tháng 3",
  "Tháng 4",
  "Tháng 5",
  "Tháng 6",
  "Tháng 7",
  "Tháng 8",
  "Tháng 9",
  "Tháng 10",
  "Tháng 11",
  "Tháng 12",
];

export const TOA_NHA = [
  "Tý",
  "Sửu",
  "Dần",
  "Mão",
  "Thìn",
  "Tỵ",
  "Ngọ",
  "Mùi",
  "Thân",
  "Dậu",
  "Tuất",
  "Hợi",
  "Giáp",
  "Ất",
  "Bính",
  "Đinh",
  "Canh",
  "Tân",
  "Nhâm",
  "Quý",
  "Cấn",
  "Tốn",
  "Khôn",
  "Càn",
];
export const KIM_LAU_NU = [
  12, 15, 17, 19, 21, 24, 26, 28, 30, 33, 35, 37, 39, 42, 44, 46, 48, 51, 53,
  55, 57, 60, 62, 64, 66, 69, 71, 73, 75,
];

// Phu chủ - Kỵ với chồng.
export const PHU_CHU = {
  Sửu: [1, 7],
  Mùi: [1, 7],
  Thìn: [2, 8],
  Tuất: [2, 8],
  Mão: [3, 9],
  Dậu: [3, 9],
  Tý: [4, 10],
  Ngọ: [4, 10],
  Dần: [6, 12],
  Thân: [6, 12],
};
// Thê chủ: Kỵ với bản thân.
export const THE_CHU = {
  Dần: [1, 7],
  Thân: [1, 7],
  Mão: [2, 8],
  Dậu: [2, 8],
  Thìn: [3, 9],
  Tuất: [3, 9],
  Tý: [5, 11],
  Ngọ: [5, 11],
  Sửu: [6, 12],
  Mùi: [6, 12],
};
export const DAI_LOI = {
  Mão: [1, 7],
  Dậu: [1, 7],
  Dần: [2, 8],
  Thân: [2, 8],
  Thìn: [4, 10],
  Tuất: [4, 10],
  Sửu: [5, 11],
  Mùi: [5, 11],
  Tý: [6, 12],
  Ngọ: [6, 12],
};
export const TIEU_LOI = {
  Tý: [1, 7],
  Ngọ: [1, 7],
  Dần: [3, 9],
  Thân: [3, 9],
  Sửu: [4, 10],
  Mùi: [4, 10],
  Thìn: [5, 11],
  Tuất: [5, 11],
  Mão: [6, 12],
  Dậu: [6, 12],
};
// Công cô: Kỵ với cha mẹ bên chồng.
export const CONG_CO = {
  Tý: [2, 8],
  Ngọ: [2, 8],
  Sửu: [3, 9],
  Mùi: [3, 9],
  Dần: [4, 10],
  Thân: [4, 10],
  Mão: [5, 11],
  Dậu: [5, 11],
  Thìn: [6, 12],
  Tuất: [6, 12],
};
// Nhạc thân: Kỵ với cha mẹ bên vợ.
export const NHAC_THAN = {
  Thìn: [1, 7],
  Tuất: [1, 7],
  Sửu: [2, 8],
  Mùi: [2, 8],
  Tý: [3, 9],
  Ngọ: [3, 9],
  Mão: [4, 10],
  Dậu: [4, 10],
  Dần: [5, 11],
  Thân: [5, 11],
};
// Hồng xa kỵ nhật: (Ảnh hưởng tới người nữ)
export const HONG_XA_KY_NHAT = [
  "Tỵ",
  "Dậu",
  "Sửu",
  "Tỵ",
  "Dậu",
  "Sửu",
  "Tỵ",
  "Dậu",
  "Sửu",
  "Tỵ",
  "Dậu",
  "Sửu",
];
// Nghênh hôn kỵ nhật - (Dễ xích mích, khó có con):
export const NGHENH_HON_KY_NHAT = ["Ất Tỵ", "Tân Hợi", "Mậu Thân", "Giáp Dần"];
export const NGU_LY = [
  "Giáp Dần",
  "Ất Mão",
  "Bính Ngọ",
  "Đinh Tỵ",
  "Mậu Thìn",
  "Mậu Tuất",
  "Kỷ Sửu",
  "Kỷ Mùi",
  "Canh Thân",
  "Tân Dậu",
  "Nhâm Tý",
  "Quý Hợi",
];
export const NGAY_SAT = {
  Mùi: ["Thân", "Tý", "Thìn"],
  Sửu: ["Dần", "Ngọ", "Tuất"],
  Thìn: ["Tỵ", "Dậu", "Sửu"],
  Tuất: ["Hợi", "Mão", "Mùi"],
};
// cô nhật tuần phòng – Dễ phải nuôi con một mình
export const CO_NHAT_TUAN_PHONG = [
  "Thìn",
  "Sửu",
  "Tuất",
  "Mùi",
  "Mão",
  "Tỵ",
  "Dậu",
  "Ngọ",
  "Dần",
  "Hợi",
  "Thân",
  "Tỵ",
];

export const BAM_CUNG_NAM = [
  "Dần",
  "Mão",
  "Thìn",
  "Tỵ",
  "Ngọ",
  "Mùi",
  "Thân",
  "Dậu",
  "Tuất",
  "Hợi",
  "Tý",
  "Sửu",
];
export const BAM_CUNG_NU = [
  "Thân",
  "Mùi",
  "Ngọ",
  "Tỵ",
  "Thìn",
  "Mão",
  "Dần",
  "Sửu",
  "Tý",
  "Hợi",
  "Tuất",
  "Dậu",
];
export const TRUNG_TANG = ["Dần", "Thân", "Tỵ", "Hợi"];
export const THIEN_DI = ["Tý", "Ngọ", "Mão", "Dậu"];
export const NHAP_MO = ["Thìn", "Tuất", "Sửu", "Mùi"];
// Kiep Sat
export const CASE3_TRUNGTANG = {
  Thân: "Tỵ",
  Tý: "Tỵ",
  Thìn: "Tỵ",
  Dần: "Hợi",
  Ngọ: "Hợi",
  Tuất: "Hợi",
  Tỵ: "Dần",
  Dậu: "Dần",
  Sửu: "Dần",
  Hợi: "Thân",
  Mão: "Thân",
  Mùi: "Thân",
};
export const CASE4_TRUNGTANG = [
  ["Canh Dần", "Canh Thân"], // 1
  ["Canh Dần", "Canh Thân"], // 2
  ["Tân Tỵ", "Tân Hợi"], //3
  ["Nhâm Dần", "Nhâm Thân"], //4
  ["Quý Tỵ", "Quý Hợi"], //5
  ["Canh Dần", "Canh Thân"], // 6
  ["Giáp Dần", "Giáp Thân"], // 7
  ["Ất Tỵ", "Ất Hợi"], // 8
  ["Canh Dần", "Canh Thân"], // 9
  ["Bính Dần", "Bính Thân"], // 10
  ["Đinh Tỵ", "Đinh Hợi"], //11
  ["Canh Dần", "Canh Thân"], // 12
];
//Tung Phuc
export const CASE5_TRUNGTANG = [
  ["Canh"], // 1
  ["Ất"], // 2
  ["Kỷ"], //3
  ["Nhâm"], //4
  ["Quý"], //5
  ["Mậu"], // 6
  ["Giáp"], // 7
  ["Tân"], // 8
  ["Kỷ"], // 9
  ["Nhâm", "Bính"], // 10
  ["Đinh", "Quý"], //11
  ["Mậu"], // 12
];

export const NGAY_KY_CHON_CAT = [
  [7, 19], // 1
  [6, 18, 30], // 2
  [6, 18, 30], //3
  [14, 16, 28], //4
  [3, 15, 27], //5
  [3, 15, 27], //6
  [1, 12, 25], //7
  [12, 24], //8
  [12, 24], //9
  [10, 22], //10
  [9, 21], //11
  [9, 21], //12
];
export const NGAY_GIO_TRUNG_TANG = [
  "Giáp",
  "Tân",
  "Mậu",
  "Bính",
  "Đinh",
  "Kỷ",
  "Canh",
  "Ất",
  "Mậu",
  "Nhâm",
  "Quý",
  "Kỷ",
];
export const NGAY_TRUNG_NHAT = ["Tỵ", "Hợi"];
export const NGAY_GIO_HA_KHOI = [
  "Hợi",
  "Ngọ",
  "Sửu",
  "Thân",
  "Mão",
  "Tuất",
  "Tỵ",
  "Tý",
  "Mùi",
  "Dần",
  "Dậu",
  "Thìn",
];

export const NGAY_GIO_THIEN_TAC = [
  "Sửu",
  "Tý",
  "Hợi",
  "Tuất",
  "Dậu",
  "Thân",
  "Mùi",
  "Ngọ",
  "Tỵ",
  "Thìn",
  "Mão",
  "Dần",
];
