export const ConvertsMonth = {
  Jan: "01",
  Feb: "02",
  Mar: "03",
  Apr: "04",
  May: "05",
  Jun: "06",
  Jul: "07",
  Aug: "08",
  Sep: "09",
  Oct: "10",
  Nov: "11",
  Dec: "12",
};
export const CAN_NAM = [
  "Canh",
  "Tân",
  "Nhâm",
  "Quý",
  "Giáp",
  "Ất",
  "Bính",
  "Đinh",
  "Mậu",
  "Kỷ",
];
export const CHI_NAM = [
  "Thân",
  "Dậu",
  "Tuất",
  "Hợi",
  "Tý",
  "Sửu",
  "Dần",
  "Mão",
  "Thìn",
  "Tỵ",
  "Ngọ",
  "Mùi",
];
export const TRUC_XUNG_HAI = {
  Tý: ["Ngọ", "Mùi"],
  Sửu: ["Mùi", "Ngọ"],
  Dần: ["Thân", "Tỵ"],
  Mão: ["Dậu", "Thìn"],
  Thìn: ["Tuất", "Mão"],
  Tỵ: ["Hợi", "Dần"],
  Ngọ: ["Tý", "Sửu"],
  Mùi: ["Sửu", "Tý"],
  Thân: ["Dần", "Hợi"],
  Dậu: ["Mão", "Tuất"],
  Tuất: ["Thìn", "Dậu"],
  Hợi: ["Tỵ", "Thân"],
};

export const NGU_HANH_TUONG_SINH = {
  Kim: ["Thuỷ", "Thổ"],
  Mộc: ["Thuỷ", "Hoả"],
  Thổ: ["Hoả", "Kim"],
  Thuỷ: ["Kim", "Mộc"],
  Hoả: ["Mộc", "Thổ"],
};
export const NGU_HANH = {
  Tý: "Thuỷ",
  Sửu: "Thổ",
  Dần: "Mộc",
  Mão: "Mộc",
  Thìn: "Thổ",
  Tỵ: "Hoả",
  Ngọ: "Hoả",
  Mùi: "Thổ",
  Thân: "Kim",
  Dậu: "Kim",
  Tuất: "Thổ",
  Hợi: "Thuỷ",

  Giáp: "Mộc",
  Ất: "Mộc",
  Bính: "Hoả",
  Đinh: "Hoả",
  Canh: "Kim",
  Tân: "Kim",
  Nhâm: "Thuỷ",
  Quý: "Thuỷ",

  Cấn: "Thổ",
  Tốn: "Mộc",
  Khôn: "Thổ",
  Càn: "Kim",
};
export const TAM_HOP = {
  Tý: ["Thân", "Thìn"],
  Sửu: ["Tỵ", "Dậu"],
  Dần: ["Ngọ", "Tuất"],
  Mão: ["Hợi", "Mùi"],

  Thìn: ["Thân", "Tý"],
  Tỵ: ["Sửu", "Dậu"],
  Ngọ: ["Dần", "Tuất"],
  Mùi: ["Hợi", "Mão"],

  Thân: ["Tý", "Thìn"],
  Dậu: ["Tỵ", "Sửu"],
  Tuất: ["Ngọ", "Dần"],
  Hợi: ["Mão", "Mùi"],
};
export const TAM_TAI = {
  Tý: ["Mão", "Dần", "Thìn"],
  Thân: ["Mão", "Dần", "Thìn"],
  Thìn: ["Mão", "Dần", "Thìn"],

  Dần: ["Thân", "Dậu", "Tuất"],
  Ngọ: ["Thân", "Dậu", "Tuất"],
  Tuất: ["Thân", "Dậu", "Tuất"],

  Hợi: ["Tỵ", "Ngọ", "Mùi"],
  Mão: ["Tỵ", "Ngọ", "Mùi"],
  Mùi: ["Tỵ", "Ngọ", "Mùi"],

  Tỵ: ["Tý", "Sửu", "Hợi"],
  Dậu: ["Tý", "Sửu", "Hợi"],
  Sửu: ["Tý", "Sửu", "Hợi"],
};
export const THO_TU = [
  "Tuất",
  "Thìn",
  "Hợi",
  "Tỵ",
  "Tý",
  "Ngọ",
  "Sửu",
  "Mùi",
  "Dần",
  "Thân",
  "Mão",
  "Dậu",
];
export const SAT_CHU_AM = [
  "Tỵ",
  "Tý",
  "Mùi",
  "Mão",
  "Thân",
  "Tuất",
  "Hợi",
  "Sửu",
  "Ngọ",
  "Dậu",
  "Dần",
  "Thìn",
];
export const SAT_CHU_DUONG = [
  "Tý",
  "Sửu",
  "Sửu",
  "Tuất",
  "Thìn",
  "Thìn",
  "Sửu",
  "Thìn",
  "Sửu",
  "Thìn",
  "Mùi",
  "Thìn",
];
export const VANG_VONG = [
  "Dần",
  "Tỵ",
  "Thân",
  "Hợi",
  "Mão",
  "Ngọ",
  "Dậu",
  "Tý",
  "Thìn",
  "Mùi",
  "Tuất",
  "Sửu",
];
export const NGUYET_PHA = [
  "Thân",
  "Dậu",
  "Tuất",
  "Hợi",
  "Tý",
  "Sửu",
  "Dần",
  "Mão",
  "Thìn",
  "Tỵ",
  "Ngọ",
  "Mùi",
];
export const TAM_NUONG = [3, 7, 13, 18, 22, 27];
export const NGUYET_KY = [5, 14, 23];
export const CAN_CHI_THANG = [
  // 'Canh', Ất
  [
    "Mậu Dần",
    "Kỷ Mão",
    "Canh Thìn",
    "Tân Tỵ",
    "Nhâm Ngọ",
    "Quý Mùi",
    "Giáp Thân",
    "Ất Dậu",
    "Bính Tuất",
    "Đinh Hợi",
    "Mậu Tý",
    "Kỷ Sửu",
  ],
  //   'Tân', Bính
  [
    "Canh Dần",
    "Tân Mão",
    "Nhâm Thìn",
    "Quý Tỵ",
    "Giáp Ngọ",
    "Ất Mùi",
    "Bính Thân",
    "Đinh Dậu",
    "Mậu Tuất",
    "Kỷ Hợi",
    "Canh Tý",
    "Tân Sửu",
  ],

  //    'Nhâm', Đinh
  [
    "Nhâm Dần",
    "Quý Mão",
    "Giáp Thìn",
    "Ất Tỵ",
    "Bính Ngọ",
    "Đinh Mùi",
    "Mậu Thân",
    "Kỷ Dậu",
    "Canh Tuất",
    "Tân Hợi",
    "Nhâm Tý",
    "Quý Sửu",
  ],

  // 'Quý', Mậu
  [
    "Giáp Dần",
    "Ất Mão",
    "Bính Thìn",
    "Đinh Tỵ",
    "Mậu Ngọ",
    "Kỷ Mùi",
    "Canh Thân",
    "Tân Dậu",
    "Nhâm Tuất",
    "Quý Hợi",
    "Giáp Tý",
    "Ất Sửu",
  ],
  //Giáp,Kỷ
  [
    "Bính Dần",
    "Đinh Mão",
    "Mậu Thìn",
    "Kỷ Tỵ",
    "Canh Ngọ",
    "Tân Mùi",
    "Nhâm Thân",
    "Quý Dậu",
    "Giáp Tuất",
    "Ất Hợi",
    "Bính Tý",
    "Đinh Sửu",
  ],
];
export const CAN_NGAY = [
  "Giáp",
  "Ất",
  "Bính",
  "Đinh",
  "Mậu",
  "Kỷ",
  "Canh",
  "Tân",
  "Nhâm",
  "Quý",
];
export const CHI_NGAY = [
  "Tý",
  "Sửu",
  "Dần",
  "Mão",
  "Thìn",
  "Tỵ",
  "Ngọ",
  "Mùi",
  "Thân",
  "Dậu",
  "Tuất",
  "Hợi",
];
export const GIO_HOANG_DAO = {
  Thân: "Tý (23-1), Sửu (1-3), Thìn (7-9), Tỵ (9-11), Mùi (13-15), Tuất (19-21)",
  Dậu: "Tý (23-1), Dần (3-5), Mão (5-7), Ngọ (11-13), Mùi (13-15), Dậu (17-19)",
  Tuất: "Dần (3-5), Thìn (7-9), Tỵ (9-11), Thân (15-17), Dậu (17-19), Hợi (21-23)",
  Hợi: "Sửu (1-3), Thìn (7-9), Ngọ (11-13), Mùi (13-15), Tuất (19-21), Hợi (21-23)",
  Tý: "Tý (23-1), Sửu (1-3), Mão (5-7), Ngọ (11-13), Thân (15-17), Dậu (17-19)",
  Sửu: "Dần (3-5), Mão (5-7), Tỵ (9-11), Thân (15-17), Tuất (19-21), Hợi (21-23)",
  Dần: " Tý (23-1), Sửu (1-3), Thìn (7-9), Tỵ (9-11), Mùi (13-15), Tuất (19-21)",
  Mão: "Tý (23-1), Dần (3-5), Mão (5-7), Ngọ (11-13), Mùi (13-15), Dậu (17-19)",
  Thìn: "Dần (3-5), Thìn (7-9), Tỵ (9-11), Thân (15-17), Dậu (17-19), Hợi (21-23)",
  Tỵ: "Sửu (1-3), Thìn (7-9), Ngọ (11-13), Mùi (13-15), Tuất (19-21), Hợi (21-23)",
  Ngọ: "Tý (23-1), Sửu (1-3), Mão (5-7), Ngọ (11-13), Thân (15-17), Dậu (17-19)",
  Mùi: "Dần (3-5), Mão (5-7), Tỵ (9-11), Thân (15-17), Tuất (19-21), Hợi (21-23)",
};
export const NGAYHOANGDAO_NGAYHACDAO = [
  // mod 6  = 0
  {
    hoangDao: ["Mão", "Tuất", "Tỵ", "Hợi", "Dần", "Thân"],
    hacDao: ["Thìn", "Sửu", "Mùi", "Dậu", "Tý", "Ngọ"],
  },
  // mod 6  = 1
  {
    hoangDao: ["Tý", "Sửu", "Tỵ", "Mùi", "Thìn", "Tuất"],
    hacDao: ["Ngọ", "Mão", "Hợi", "Dậu", "Dần", "Thân"],
  },
  // mod 6  = 2
  {
    hoangDao: ["Dần", "Mão", "Dậu", "Mùi", "Ngọ", "Tý"],
    hacDao: ["Thân", "Tỵ", "Hợi", "Sửu", "Thìn", "Tuất"],
  },
  // mod 6  = 3
  {
    hoangDao: ["Thìn", "Dậu", "Tỵ", "Hợi", "Thân", "Dần"],
    hacDao: ["Tuất", "Mùi", "Mão", "Sửu", "Ngọ", "Tý"],
  },
  // mod 6  = 4
  {
    hoangDao: ["Ngọ", "Sửu", "Thìn", "Mùi", "Tuất", "Hợi"],
    hacDao: ["Thân", "Tý", "Mão", "Tỵ", "Dậu", "Dần"],
  },
  // mod 6  = 5
  {
    hoangDao: ["Mão", "Sửu", "Thân", "Dậu", "Tý", "Ngọ"],
    hacDao: ["Dần", "Mùi", "Hợi", "Tỵ", "Tuất", "Dậu"],
  },
];
export const CAN = [
  "Giáp",
  "Ất",
  "Bính",
  "Đinh",
  "Mậu",
  "Kỷ",
  "Canh",
  "Tân",
  "Nhâm",
  "Quý",
];
export const CHI = [
  "Tý",
  "Sửu",
  "Dần",
  "Mão",
  "Thìn",
  "Tỵ",
  "Ngọ",
  "Mùi",
  "Thân",
  "Dậu",
  "Tuất",
  "Hợi",
];
export const TUAN = [
  "Chủ Nhật",
  "Thứ Hai",
  "Thứ Ba",
  "Thứ Tư",
  "Thứ Năm",
  "Thứ Sáu",
  "Thứ Bảy",
];

export const C_H = [
  0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
  0, 0,
];
export const THANG_AM_VN = [
  "Một",
  "Hai",
  "Ba",
  "Bốn",
  "Năm",
  "Sáu",
  "Bảy",
  "Tám",
  "Chín",
  "Mười",
  "Mười một",
  "Mười hai",
];
export const TIETKHI = {
  0: "Xuân phân",
  15: "Thanh minh",
  30: "Cốc vũ",
  45: "Lập hạ",
  60: "Tiểu mãn",
  75: "Mang chủng",
  90: "Hạ chí",
  105: "Tiểu thử",
  120: "Đại thử",
  135: "Lập thu",
  150: "Xử thử",
  165: "Bạch lộ",
  180: "Thu phân",
  195: "Hàn lộ",
  210: "Sương giáng",
  225: "Lập đông",
  240: "Tiểu tuyết",
  255: "Đại tuyết",
  270: "Đông chí",
  285: "Tiểu hàn",
  300: "Đại hàn",
  315: "Lập xuân",
  330: "Vũ thủy",
  345: "Kinh trập",
};
export const ObjectTruc = {
  Kiến: {
    CanLam: {
      "trong-cay": "Trồng cây",
      "khai-truong": "Khai trương",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhap-kho": "Ngày nhập kho",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",
    },
    KhongLam: {
      "dong-tho": "Động thổ",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "dao-gieng": "Đào giếng",
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "ha-tieu": "Hạ tiểu",
    },
  },
  Trừ: {
    CanLam: {
      "boc-bat-huong": "Bốc bát hương",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",
    },
    KhongLam: {
      "khai-truong": "Khai trương",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
    },
  },
  Mãn: {
    CanLam: {
      "sua-chua": "Sửa chữa",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",
    },
    KhongLam: {
      "ngay-nham-chuc": "Ngày nhậm chức",
      "kien-tung": "Kiện tụng",
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "ha-tieu": "Hạ tiểu",
    },
  },
  Bình: {
    CanLam: {
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nhap-kho": "Ngày nhập kho",
      "ngay-xuat-hang": "Ngày xuất hàng",
    },
    KhongLam: {},
  },
  Định: {
    CanLam: {
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nhap-kho": "Ngày nhập kho",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
    },
    KhongLam: {
      "kien-tung": "Kiện tụng",
    },
  },
  Chấp: {
    CanLam: {
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
    },
    KhongLam: {
      "kien-tung": "Kiện tụng",
      "khai-truong": "Khai trương",
      "xuat-hanh": "Xuất hành",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
    },
  },
  Phá: {
    CanLam: {
      "pha-do": "Phá dỡ",
      "chuyen-nha": "Chuyển nhà",
      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",
    },
    KhongLam: {
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "trong-cay": "Trồng cây",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "ban-nha": "Bán nhà",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },
  Nguy: {
    CanLam: {
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",
    },
    KhongLam: {
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "trong-cay": "Trồng cây",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },
  Thành: {
    CanLam: {
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "trong-cay": "Trồng cây",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "xuat-hanh": "Xuất hành",

      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",

      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",
      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu iêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {
      "kien-tung": "Kiện tụng",
    },
  },
  Thu: {
    CanLam: {
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
    },
    KhongLam: {
      "ha-huyet": "Hạ huyệt",
      "ta-mo": "Tạ mộ",
    },
  },
  Khai: {
    CanLam: {
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "trong-cay": "Trồng cây",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",

      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",

      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",

      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",
      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu iêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",

      "ta-mo": "Tạ mộ",
    },
    KhongLam: {
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
    },
  },
  Bế: {
    CanLam: {
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "lap-gieng": "Lắp giếng",
    },
    KhongLam: {
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "trong-cay": "Trồng cây",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dao-gieng": "Đào giếng",

      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",

      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",

      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",

      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",
      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu iêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },
};

export const ObjectTu = {
  Giác: {
    CanLam: {
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
    },
    KhongLam: {
      "ha-huyet": "Hạ huyệt",
      "ha-tieu": "Hạ tiểu",
    },
  },
  Cang: {
    CanLam: {},
    KhongLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },
  Đê: {
    CanLam: {
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
    },
    KhongLam: {
      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },
  Phòng: {
    CanLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {},
  },
  Tâm: {
    CanLam: {},
    KhongLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },
  Vỹ: {
    CanLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {},
  },
  Cơ: {
    CanLam: {
      "khai-truong": "Khai trương",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",

      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",
    },
    KhongLam: {},
  },
  Đẩu: {
    CanLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "nhap-trach": "Nhập trạch",
      "khai-truong": "Khai trương",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "ha-tieu": "Hạ tiểu",
    },
    KhongLam: {},
  },
  Ngưu: {
    CanLam: {},
    KhongLam: {
      "dong-tho": "Động thổ",
      "nhap-trach": "Nhập trạch",
      "khai-truong": "Khai trương",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",
    },
  },
  Nữ: {
    CanLam: {},
    KhongLam: {
      "ngay-nham-chuc": "Ngày nhậm chức",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",
    },
  },
  Hư: {
    CanLam: {},
    KhongLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },

  Nguy: {
    CanLam: {},
    KhongLam: {
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "dung-bia": "Dựng bia",
      "ha-huyet": "Hạ huyệt",
    },
  },
  Thất: {
    CanLam: {
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "khai-truong": "Khai trương",
      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {},
  },
  Bích: {
    CanLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {},
  },
  Khuê: {
    CanLam: {
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
    },
    KhongLam: {
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "dong-tho": "Động thổ",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "dao-gieng": "Đào giếng",
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "ha-tieu": "Hạ tiểu",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "dung-bia": "Dựng bia",
      "ha-huyet": "Hạ huyệt",
    },
  },
  Lâu: {
    CanLam: {
      "sua-chua": "Sửa chữa",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "trong-cay": "Trồng cây",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "lap-gieng": "Lắp giếng",
      "dao-gieng": "Đào giếng",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",

      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",

      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",

      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",
      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu iêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {
      "ngay-nham-chuc": "Ngày nhậm chức",
      "kien-tung": "Kiện tụng",
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "ha-tieu": "Hạ tiểu",
    },
  },
  Vị: {
    CanLam: {
      "boc-bat-huong": "Bốc bát hương",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",
      "sua-chua": "Sửa chữa",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "trong-cay": "Trồng cây",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "lap-gieng": "Lắp giếng",
      "dao-gieng": "Đào giếng",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",

      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",

      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",

      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",
      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu iêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {},
  },
  Mão: {
    CanLam: {},
    KhongLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },
  Tất: {
    CanLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {},
  },
  Chủy: {
    CanLam: {},
    KhongLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },

  Sâm: {
    CanLam: {
      "sua-chua": "Sửa chữa",
      "khai-truong": "Khai trương",
      "nhap-hoc": "Nhập học",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
    },
    KhongLam: {
      "ha-huyet": "Hạ huyệt",
      "ha-tieu": "Hạ tiểu",
    },
  },
  Tỉnh: {
    CanLam: {
      "sua-chua": "Sửa chữa",
      "khai-truong": "Khai trương",
      "nhap-hoc": "Nhập học",
    },
    KhongLam: {
      "ha-huyet": "Hạ huyệt",
      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
    },
  },
  Quỷ: {
    CanLam: {
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",
      "ha-tieu": "Hạ tiểu",
    },
    KhongLam: {
      "dong-tho": "Động thổ",
      "khai-truong": "Khai trương",
      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",
    },
  },
  Liễu: {
    CanLam: {},
    KhongLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
  },
  Tinh: {
    CanLam: {
      "khoi-cong": "Khởi công",
    },
    KhongLam: {
      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",
    },
  },
  Trương: {
    CanLam: {},
    KhongLam: {
      "sua-chua": "Sửa chữa",
      "pha-do": "Phá dỡ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "dong-tho": "Động thổ",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
    },
  },
  Dực: {
    CanLam: {
      "dong-tho": "Động thổ",
      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",
    },
    KhongLam: {
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
    },
  },

  Chẩn: {
    CanLam: {
      "trong-cay": "Trồng cây",
      "khoi-cong": "Khởi công",
      "sua-chua": "Sửa chữa",
      "dong-tho": "Động thổ",
      "do-mong": "Đổ móng",
      "do-mai": "Đổ mái",
      "cat-noc": "Cất nóc",
      "mo-cong": "Mở cổng",
      "boi-hoan-long-mach": "Bồi hoàn long mạch",
      "nhap-trach": "Nhập trạch",
      "ta-dat": "Tạ đất",
      "khanh-thanh": "Khánh thành",
      "khai-truong": "Khai trương",
      "mo-cua-hang": "Mở cửa hàng",
      "chuyen-nha": "Chuyển nhà",
      "ban-nha": "Bán nhà",
      "dap-dap": "Đắp đập",
      "ngan-de": "Ngăn đê",
      "dao-gieng": "Đào giếng",
      "lap-gieng": "Lắp giếng",
      "nhap-hoc": "Nhập học",
      "kien-tung": "Kiện tụng",
      "xuat-hanh": "Xuất hành",
      "mua-ban-lon":
        "Mua bán lớn (Hợp đồng: Mua xe, bàn giao xe, mua nhà, mua đất,…)",
      "ngay-nham-chuc": "Ngày nhậm chức",
      "ngay-nhan-cong-viec-moi": "Ngày nhận công việc mới",
      "ngay-thay-doi-cong-viec": "Ngày thay đổi công việc",
      "ngay-nhap-kho": "Ngày nhập kho",
      "xuat-tien": "Xuất tiền",
      "ngay-xuat-hang": "Ngày xuất hàng",
      "ngay-xuat-hanh": "Xuất hành",
      "ngay-ra-mat-san-pham": "Ngày ra mắt sản phẩm/dự án sáng tạo",
      "ngay-thuc-hien-du-an":
        "Ngày thực hiện dự án mới (thói quen mới/kế hoạch mới)",
      "giao-dich": "Giao dịch, ký kết hợp đồng, đặt cọc",
      "cung-xe-moi": "Cúng xe mới",
      "tuyen-dung": "Tuyển dụng",
      "thue-nguoi-lam": "Thuê người làm",
      "to-chuc-cac-su-kien": "Tổ chức các sự kiện",

      "chuyen-vi-tri-ban-tho": "Chuyển vị trí bàn thờ",
      "boc-bat-huong": "Bốc bát hương",
      "tu-tao-lai-ban-tho-": "Tu tạo lại bàn thờ",
      "dang-them-vat-pham": "Dâng thêm vât phẩm",
      "them-bat-huong": "Thêm bát hương cho bàn thờ",
      "thay-ban-tho": "Thay bàn thờ mới",
      "giai-xa-ban-tho": "Giải xá bàn thờ",
      "ngay-cung-le-dau-nam-cuoi-nam": "Ngày cúng lễ đầu năm, cuối năm",
      "le-cau":
        "Lễ cầu an, cầu siêu, cầu phúc, cầu tài, cầu lộc, cầu tự, cầu duyên,…",

      "ngay-kham-benh": "Ngày khám bệnh",
      "ngay-phau-thuat": "Ngày phẫu thuật",

      "ngay-mai-moi": "Ngày mai mối",
      "ngay-dam-ngo": "Ngày dạm ngõ",
      "ngay-an-hoi": "Ngày ăn hỏi (đính hôn)",
      "ngay-lai-mat": "Lại mặt",
      "ngay-dang-ki-ket-hon": "Ngày đăng kí kết hôn",
      "ngay-cuoi": "Ngày cưới",

      "tinh-trung-tang": "Tính trùng tang",
      "kham-niem": "Khâm niệm",
      "nhap-quan": "Nhập quan",
      "di-quan": "Di quan",
      "ha-huyet": "Hạ huyệt",

      "dong-tho-xay-ho": "Động thổ xây hố",
      "dao-mo-cu-mo-lap-van": "Đào mộ cũ - Mở lắp ván",
      "kham-liem": "Khâm liệm",
      "ha-tieu": "Hạ tiểu",
      "dung-bia": "Dựng bia",
      "ta-mo": "Tạ mộ",
    },
    KhongLam: {},
  },
};
