import { Inter } from "next/font/google";
import "./globals.css";
import Favicon from "../../public/favicon/favicon.ico";
import { LocalizationProvide } from "@Root/app/LocalProviderApp";
import Head from "next/head";
import ResponsiveAppBar from "@Root/app/components/ResponsiveNav";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Thầy Huyền Học: Xem ngày, Phong Thủy, Kỳ Môn",
  description: "Generated by ThayAI",
  icons: [{ rel: "icon", url: Favicon.src }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body className={inter.className}>
        <div className=" fixed w-full z-10">
          <ResponsiveAppBar />
        </div>
        <LocalizationProvide children={children}></LocalizationProvide>
      </body>
    </html>
  );
}
