import { Inter } from "next/font/google";
import "./globals.css";

import { LocalizationProvide } from "@Root/app/LocalProviderApp";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Thầy Huyền Học: Xem ngày, Phong Thủy, Kỳ Môn",
  description: "Generated by ThayAI",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LocalizationProvide children={children}></LocalizationProvide>
      </body>
    </html>
  );
}
